/**
 * Purpose: Fetch run data from static JSON files.
 * Exports: fetchRuns, fetchRun, fetchPlan, fetchDashboardIndex, fetchLatestAggregate
 *
 * Data is loaded from the results directory via Vite's dev server.
 * All fetched JSON is validated with Zod schemas at this boundary.
 */
import {
	DashboardIndexLegacyOrV2Schema,
	LeaderboardAggregateSchema,
	RunPlanSchema,
	RunResultSchema,
} from "./schemas";
import type {
	DashboardIndex,
	LeaderboardAggregate,
	RunListItem,
	RunPlan,
	RunResult,
} from "./types";

/**
 * Base path for published results.
 *
 * Note: Use BASE_URL so static deployments under a sub-path still work.
 * Example: BASE_URL="/bench/" -> "/bench/results"
 */
const RESULTS_BASE = `${import.meta.env.BASE_URL.replace(/\/$/, "")}/results`;

/**
 * Normalizes legacy and v2 index payloads to a stable v2 shape.
 *
 * @param raw - Parsed and validated index payload
 * @returns Normalized dashboard index object
 */
function normalizeDashboardIndex(
	raw: ReturnType<typeof DashboardIndexLegacyOrV2Schema.parse>,
): DashboardIndex {
	if (Array.isArray(raw)) {
		return {
			schemaVersion: 2,
			generatedAt: new Date(0).toISOString(),
			latestCheckpointId: null,
			runs: raw,
			checkpoints: [],
		};
	}
	return raw;
}

/**
 * Creates an empty aggregate payload when no aggregate artifact exists yet.
 *
 * @param checkpointId - Checkpoint ID from dashboard index metadata
 * @returns Empty aggregate payload
 */
function createEmptyAggregate(
	checkpointId: string | null,
): LeaderboardAggregate {
	return {
		schemaVersion: 1,
		generatedAt: new Date(0).toISOString(),
		checkpointId: checkpointId ?? "unknown",
		summary: {
			runsConsidered: 0,
			runsMatched: 0,
			rawItems: 0,
			dedupedItems: 0,
			machines: 0,
			automatedScoreItems: 0,
			frontierEvalItems: 0,
		},
		machines: [],
		items: [],
	};
}

/**
 * Fetches and normalizes dashboard index metadata.
 *
 * Supports legacy array-based `index.json` and v2 object format.
 */
export async function fetchDashboardIndex(): Promise<DashboardIndex> {
	const response = await fetch(`${RESULTS_BASE}/index.json`);
	if (!response.ok) {
		if (response.status === 404) {
			console.warn(
				"No runs index found. Run `bun dashboard:index` to generate apps/dashboard/public/results/index.json.",
			);
			return {
				schemaVersion: 2,
				generatedAt: new Date(0).toISOString(),
				latestCheckpointId: null,
				runs: [],
				checkpoints: [],
			};
		}
		throw new Error(`Failed to fetch runs index: ${response.status}`);
	}
	const data = await response.json();
	const parsed = DashboardIndexLegacyOrV2Schema.parse(data);
	return normalizeDashboardIndex(parsed);
}

/**
 * Fetches the list of all available runs from index.json.
 * The index is generated by the build-index script.
 * @throws Error if fetch fails, index doesn't exist, or validation fails
 */
export async function fetchRuns(): Promise<RunListItem[]> {
	const index = await fetchDashboardIndex();
	return index.runs;
}

/**
 * Fetches a single run's result data.
 * @param runId - The run ID (directory name in results/)
 * @throws Error if run doesn't exist, fetch fails, or validation fails
 */
export async function fetchRun(runId: string): Promise<RunResult> {
	const response = await fetch(`${RESULTS_BASE}/${runId}/run.json`);
	if (!response.ok) {
		throw new Error(`Failed to fetch run ${runId}: ${response.status}`);
	}
	const data = await response.json();
	return RunResultSchema.parse(data);
}

/**
 * Fetches a run's plan data.
 * @param runId - The run ID (directory name in results/)
 * @throws Error if plan doesn't exist, fetch fails, or validation fails
 */
export async function fetchPlan(runId: string): Promise<RunPlan> {
	const response = await fetch(`${RESULTS_BASE}/${runId}/plan.json`);
	if (!response.ok) {
		throw new Error(`Failed to fetch plan ${runId}: ${response.status}`);
	}
	const data = await response.json();
	return RunPlanSchema.parse(data);
}

/**
 * Fetches both run and plan data for a run.
 * @param runId - The run ID (directory name in results/)
 * @returns Object with run and plan data
 */
export async function fetchRunWithPlan(
	runId: string,
): Promise<{ run: RunResult; plan: RunPlan }> {
	const [run, plan] = await Promise.all([fetchRun(runId), fetchPlan(runId)]);
	return { run, plan };
}

/**
 * Fetches the latest checkpoint aggregate payload used by leaderboard view.
 *
 * When aggregate artifacts do not exist yet, returns an empty aggregate fallback.
 */
export async function fetchLatestAggregate(): Promise<LeaderboardAggregate> {
	const response = await fetch(`${RESULTS_BASE}/aggregates/latest.json`);
	if (response.status === 404) {
		const index = await fetchDashboardIndex();
		return createEmptyAggregate(index.latestCheckpointId);
	}
	if (!response.ok) {
		throw new Error(`Failed to fetch latest aggregate: ${response.status}`);
	}
	const data = await response.json();
	return LeaderboardAggregateSchema.parse(data);
}
