/**
 * Purpose: Fetch run data from static JSON files.
 * Exports: fetchRuns, fetchRun, fetchPlan
 *
 * Data is loaded from the results directory via Vite's dev server.
 * All fetched JSON is validated with Zod schemas at this boundary.
 */
import { RunListSchema, RunPlanSchema, RunResultSchema } from "./schemas";
import type { RunListItem, RunPlan, RunResult } from "./types";

/** Base path for results - served via Vite dev server */
const RESULTS_BASE = "/results";

/**
 * Fetches the list of all available runs from index.json.
 * The index is generated by the build-index script.
 * @throws Error if fetch fails, index doesn't exist, or validation fails
 */
export async function fetchRuns(): Promise<RunListItem[]> {
	const response = await fetch(`${RESULTS_BASE}/index.json`);
	if (!response.ok) {
		if (response.status === 404) {
			// Index doesn't exist yet - return empty list
			console.warn(
				"No runs index found. Run `bun dashboard:index` to generate it.",
			);
			return [];
		}
		throw new Error(`Failed to fetch runs index: ${response.status}`);
	}
	const data = await response.json();
	return RunListSchema.parse(data);
}

/**
 * Fetches a single run's result data.
 * @param runId - The run ID (directory name in results/)
 * @throws Error if run doesn't exist, fetch fails, or validation fails
 */
export async function fetchRun(runId: string): Promise<RunResult> {
	const response = await fetch(`${RESULTS_BASE}/${runId}/run.json`);
	if (!response.ok) {
		throw new Error(`Failed to fetch run ${runId}: ${response.status}`);
	}
	const data = await response.json();
	return RunResultSchema.parse(data);
}

/**
 * Fetches a run's plan data.
 * @param runId - The run ID (directory name in results/)
 * @throws Error if plan doesn't exist, fetch fails, or validation fails
 */
export async function fetchPlan(runId: string): Promise<RunPlan> {
	const response = await fetch(`${RESULTS_BASE}/${runId}/plan.json`);
	if (!response.ok) {
		throw new Error(`Failed to fetch plan ${runId}: ${response.status}`);
	}
	const data = await response.json();
	return RunPlanSchema.parse(data);
}

/**
 * Fetches both run and plan data for a run.
 * @param runId - The run ID (directory name in results/)
 * @returns Object with run and plan data
 */
export async function fetchRunWithPlan(
	runId: string,
): Promise<{ run: RunResult; plan: RunPlan }> {
	const [run, plan] = await Promise.all([fetchRun(runId), fetchPlan(runId)]);
	return { run, plan };
}
